insert into CHECKS (name,question,who,when,whereby) values ('Lieferanmeldung','CRUD Planung abgeschlossen?','PO','Anfang Sprint','Jira-Status/Sprintplaning');
insert into Checks (name,question,who,when,whereby) values ('SW Verfügbar','Sind die Artifactory-Packages vorhanden?','RM / ST','Ende Sprint','Artifactory');
insert into checks (name,question,who,when,whereby) values ('Release Notes','Liegt eine passende Release_Notes.yaml vor?','RM','Mitte Sprint','yaml');
insert into checks (name,question,who,when,whereby) values ('Dependencies','Liegt eine passende Dependencies.yaml vor?','RM','Mitte Sprint','yaml');
insert into checks (name,question,who,when,whereby) values ('Config EU','Sind die Konfigurationen (Attribute und Werte) für EU/TS validiert?','PO / LeadDev','Anfang Sprint','SVN /env/ts');
insert into checks (name,question,who,when,whereby) values ('Config IEU','Sind Konfigwerte für IEU eingetragen?','ST','Anfang Sprint','SVN /env/ieu');
insert into checks (name,question,who,when,whereby) values ('Config ITU','Sind die Configs für die ITU vorbereitet?','RM / ST','Ende Sprint','yaml und mehr');
insert into checks (name,question,who,when,whereby) values ('Abnahme IEU','PO gibt OK für Userstory','PO','Ende Sprint','Jira-Status/Review-Results');
insert into checks (name,question,who,when,whereby) values ('Integrationstest IEU','Autom. Technischer Smoke-Durchschstich','ITT','Ende Sprint','TMT?');
insert into checks (name,question,who,when,whereby) values ('ITU-Umgebung verfügbar','Sind Alive Checks erfolgreich? (ping etc.)','RM/ST','Mitte Sprint','Jenkins');
insert into checks (name,question,who,when,whereby) values ('Deployment Ressourcen verfügbar','Wer muss zum Deployment vorort / erreichbar sein?','RM /RTE / SM','Mitte Sprint','Runbook');
insert into checks (name,question,who,when,whereby) values ('CI/CD verfügbar','Jenkins Pipeline vorhanden und getestet?','ST','Mitte Sprint','Jenkins');
insert into checks (name,question,who,when,whereby) values ('Testplan verfügbar','Liegt der Testplan inkl. Testdaten vor?','ITT','Ende Sprint','Wiki');
insert into checks (name,question,who,when,whereby) values ('Deploymentplan','Runbook','RM / RTE','Mitte Sprint','Runbook');
insert into checks (name,question,who,when,whereby) values ('Deployment-Freigabe','CAB Result','CAB','CAB Meeting','Handsup');
