insert into ENVIRONMENT (short_name,name,state,type) values ('LEU1','Lokale Entwicklungsumgebung für Anwendungsfall ABC','planned','Docker');
insert into ENVIRONMENT (short_name,name,state,type) values ('LEU2','Lokale Entwicklungsumgebung für Anwendungsfall DEF','planned','Docker');
insert into ENVIRONMENT (short_name,name,state,type) values ('LEU3','Lokale Entwicklungsumgebung für Anwendungsfall XYZ','planned','AwsAmi');
insert into ENVIRONMENT (short_name,name,state,type) values ('EU','Primäre Entwicklungsumgebung','live','VM');
insert into ENVIRONMENT (short_name,name,state,type) values ('IEU','Integrierte Entwicklungsumgebung','live','VM');
insert into ENVIRONMENT (short_name,name,state,type) values ('ITU','Integrierte Testumgebung','live','Hybrid');
insert into ENVIRONMENT (short_name,name,state,type) values ('ITU2','Schattenbetrieb','planned','na');
insert into ENVIRONMENT (short_name,name,state,type) values ('LUP','Umgebung für NFA Tests, wie Pen oder LuP','planned','na');
insert into ENVIRONMENT (short_name,name,state,type) values ('UAT','Abnahmeumgebung','planned','na');
insert into ENVIRONMENT (short_name,name,state,type) values ('WAU','Wartungsumgebung','planned','na');
insert into ENVIRONMENT (short_name,name,state,type) values ('PRD','Produktionsumgebung','planned','na');